### Health check

GET http://localhost:3000/health HTTP/1.1

### GET tasks
GET http://localhost:3000/v1/tasks?search=task&completed=0&orderBy=created_at-desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzQxMjcwODUwLCJleHAiOjE3NDEyNzgwNTAsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.MaP_JicaH86F_MvFSeMf28MJmQkCNHD8AImwzRBYc-X93-ld4wUo7sC9xT7oa78mCj23wcOr9MmcjhrVPuLtWLWHKZPnAYaPLouqJV8NwfoZwYY7XGoe6oOU7wd4Un9ug2X1ySP_3rUv7H_23EwV2qPD3kQB6wC7jwkEJ_LaqJLW1g1L_ZxsCQV1swg_vA9-iYJmc_O_fZc4NloSmoN-x_6hD-dv__L5EftBhxHANJcZKRKN2Y_Xiu55r1hHwHJNNYMWHoD6H5LHjMRM2N3MhB2vvo2ep7olfznYW4-QdaV4Z7QZDrKVW5K8m6Q4-dkySCfUW9uE2TWwLW9Ia2L3Lg

### GET task by ID
GET http://localhost:3000/v1/tasks/cm5fm8t1z0001840lc1070727 HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzQxMjcwODUwLCJleHAiOjE3NDEyNzgwNTAsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.MaP_JicaH86F_MvFSeMf28MJmQkCNHD8AImwzRBYc-X93-ld4wUo7sC9xT7oa78mCj23wcOr9MmcjhrVPuLtWLWHKZPnAYaPLouqJV8NwfoZwYY7XGoe6oOU7wd4Un9ug2X1ySP_3rUv7H_23EwV2qPD3kQB6wC7jwkEJ_LaqJLW1g1L_ZxsCQV1swg_vA9-iYJmc_O_fZc4NloSmoN-x_6hD-dv__L5EftBhxHANJcZKRKN2Y_Xiu55r1hHwHJNNYMWHoD6H5LHjMRM2N3MhB2vvo2ep7olfznYW4-QdaV4Z7QZDrKVW5K8m6Q4-dkySCfUW9uE2TWwLW9Ia2L3Lg

### Create task
POST http://localhost:3000/v1/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzQwMjQwNTUxLCJleHAiOjE3NDAyNDc3NTEsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.QsYnmrrwb2PLqpZl7-llxyGg3QeD9kZpU71qhhKAjlmRzeOHQuoB7cSIVp_03lj8gAsE7Ty09bvHheu7-ZCBfoji1VWeQkRe_4rXK_XrKSm9lQASSCWGVz5URDEK5R4tsasnIv8QMNy-aFVbta7NA0BpCt0MyCDd7yM5f9zaKLb9WYNAbuw0vRb8wv4rkJty_F6PloCANyvAGN1VaF0o_xdLN4nD6wt6oqyEpphSCCbckKGZMp7wYmmzKk9zxd7tmVF3V3DyvRBMXutSDLW5zWDX-tplz1EikGEVFKXanaSqGerVV9zcHC4xTGbrzJrI2j3FiVb2LOXCiooGtfpG1A

{
    "name": "Implement Strategy Pattern"
}

### Mark Task as Complete
PATCH http://localhost:3000/v1/tasks/cm6cm4bm500018jych8pkz0s2/complete
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzQxMjcwODUwLCJleHAiOjE3NDEyNzgwNTAsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.MaP_JicaH86F_MvFSeMf28MJmQkCNHD8AImwzRBYc-X93-ld4wUo7sC9xT7oa78mCj23wcOr9MmcjhrVPuLtWLWHKZPnAYaPLouqJV8NwfoZwYY7XGoe6oOU7wd4Un9ug2X1ySP_3rUv7H_23EwV2qPD3kQB6wC7jwkEJ_LaqJLW1g1L_ZxsCQV1swg_vA9-iYJmc_O_fZc4NloSmoN-x_6hD-dv__L5EftBhxHANJcZKRKN2Y_Xiu55r1hHwHJNNYMWHoD6H5LHjMRM2N3MhB2vvo2ep7olfznYW4-QdaV4Z7QZDrKVW5K8m6Q4-dkySCfUW9uE2TWwLW9Ia2L3Lg

### GET projects
GET http://localhost:3000/v1/projects HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzM3OTI4ODQwLCJleHAiOjE3Mzc5MzYwNDAsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.mxRpkUrh8mauklE47FxxgS2cU6YFpaoyZkLwz8QQId0q719S1i7PDiQrEwrEcc8-O5KSzOWT1lGM0lenyX0A4NklNvqZmzNyq_EnoH8MiAdt1W-z2kjwtJdcn0zQRZjOUd0eOGsn0Wb9mcoTRqattAK0pFUS7dPzkjSmfa24Sd6RDjEmdudwymuiWhk0dB97_2A5hTbggFYSXP06dpuiIyw8q_eO96DiDmi0_P0zexME7Bz-AW5pftmJazcBEHwFkgmMV_cabtNvglbCNTQztFpJDXtTEJ4SaQRw_r30yQeDzrzYrFtqiG_bk5uYvnDKdlufb84NzpcRCUOcGAbNCg

### GET project by ID
GET http://localhost:3000/v1/projects/1 HTTP/1.1

### GET project's tasks
GET http://localhost:3000/v1/projects/1/tasks HTTP/1.1